[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "xarray-graph"
description = "PyQt/PySide UI for graphing (x,y) slices of Xarray datasets."
dynamic = ["version"]
authors = [
    {name = "Marcel Goldschen-Ohm", email = "goldschen-ohm@utexas.edu"},
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.26.2",
    "xarray>=2023.12.0",
    "qtpy>=2.4.1",
    "qtawesome>=1.3.0",
    "pyqt-ext>=2024.9.2",
    "pyqtgraph-ext>=2024.9.0",
    "xarray-treeview @ git+https://github.com/marcel-goldschen-ohm/xarray-treeview",
    "qtconsole>=5.5.2",
    "scipy>=1.11.4",
    "lmfit>=1.2.2",
]
readme = "README.md"
keywords = ["PyQt", "PySide", "xarray", "graph"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
]


[project.urls]
homepage = "https://github.com/marcel-goldschen-ohm/xarray-graph"
repository = "https://github.com/marcel-goldschen-ohm/xarray-graph"
issues = "https://github.com/marcel-goldschen-ohm/xarray-graph/issues"


[project.scripts]
xarray-graph = "xarray_graph.__main__:main"


[tool.pdm]
distribution = true


[tool.pdm.version]
source = "scm"


[tool.pdm.dev-dependencies]
# file paths assume local dev packages are in same dir as this package
dev = [
    "-e pyqt-ext @ file:///${PROJECT_ROOT}/../pyqt-ext",
    "-e pyqtgraph-ext @ file:///${PROJECT_ROOT}/../pyqtgraph-ext",
    #"-e xarray-treeview @ file:///${PROJECT_ROOT}/../xarray-treeview",
]
lint = [
    "flake8",
]
test = [
    "pytest",
    "pytest-cov",
]
